
schema {
  query: Query
  mutation: Mutation
}

type Token {
    token: String!
}

type Rhetoric {
    _id: ID
    dateCreated: String!
    active: Boolean!
    slug: String!
    pro: Boolean!
    title: String!
    approved: Boolean!
    dateApproved: String
    approvedBy: String
    approvalCommentary: String
    bulletPoints: [BulletPoint!]!
    resources: [Resource!]!
    opinions: [Opinion!]!
    edits: [Edit!]!
    originalDonation: Donation
    accruedVotes: Float!
}

type BulletPoint {
    _id: ID
    dateCreated: String!
    active: Boolean!
    slug: String!
    pro: Boolean!
    content: String!
    approved: Boolean!
    dateApproved: String
    approvedBy: User
    approvalCommentary: String
    edits: [Edit!]!
    opinions: [Opinion!]!
    originalDonation: Donation
    accruedVotes: Float
}

type Resource {
    _id: ID
    dateCreated: String!
    active: Boolean!
    slug: String!
    pro: Boolean!
    title: String!
    media: String!
    link: String!
    approved: Boolean!
    dateApproved: String
    approvedBy: User
    approvalCommentary: String
    edits: [Edit!]!
    opinions: [Opinion!]!
    originalDonation: Donation
    accruedVotes: Float
}

type Opinion {
    _id: ID
    dateCreated: String!
    createdBy: String!
    slug: String!
    pro: Boolean!
    opinion: String!
    approved: Boolean!
    dateApproved: String
    approvedBy: String
    approvalCommentary: String
    documentID: ID!
    onModel: String!
    originalDonation: Donation!
}

type Edit {
    _id: ID
    dateCreated: String!
    createdBy: String!
    slug: String!
    pro: Boolean!
    oldDocumentID: ID!
    newDocumentID: ID!
    onModel: String!
    approved: Boolean!
    dateApproved: String
    approvedBy: String
    approvalCommentary: String
    originalDonation: Donation!
}

type Donation {
    _id: ID
    dateCreated: String!
    createdBy: String!
    slug: String!
    pro: Boolean!
    amount: Float!
    documentID: ID!
    onModel: String!
    active: Boolean!
    paid: Boolean!
    invoiceID: String!
    invoiceURL: String!
    votingDonation: Boolean
    upVote: Boolean
}

type Certificate {
    _id: ID
    dateCreated: String!
    active: Boolean!
    name: String!
    pro: Boolean!
    originalDonation: Donation!
}

type User {
    _id: ID
    dateCreated: String!
    username: String!@unique
    email: String!@unique
    emailVerified: Boolean!
    active: Boolean!
    password: String!
    admin: Boolean!
}

type Crypto {
    _id: ID
    ticker: String!
    valueUSD: Float!
}

type Query {
    currentUser: User
    userSpecificActivity: [Donation]

    argumentSpecificRhetoric(pro: Boolean!, slug: String!): Rhetoric
    argumentSpecificAmountDonated(pro: Boolean!, slug: String!): Float
    argumentSpecificDonations(pro: Boolean, slug: String): [Donation]

    docIDSpecificDonation(_id: ID!): Donation
    docIDSpecificAmountDonated(pro: Boolean!, slug: String!, onModel: String!, documentID: ID!): Float
    docIDSpecificRhetoric(_id: ID!): Rhetoric
    docIDSpecificBulletPoint(_id: ID!): BulletPoint
    docIDSpecificResource(_id: ID!): Resource

    allRhetoric(pro: Boolean!): [Rhetoric]
    allUnapprovedEdits: [Edit]
    allUnapprovedOpinions: [Opinion]
    
    topLastRandomOpinions(_id: String!, onModel: String!): [Opinion]

    donationSpecificOpinion(_id: ID!): Opinion

    cryptoValue(ticker: String!): Float
}

type Mutation {
    signinUser(email: String!, password: String!): Token
    signupUser(username: String!, email: String!, password: String!): Boolean
    verifyEmail(token: String!): Token
    resendEmail(email: String!): Boolean
    setUserAllegiance(allegiance: String!): Token

    submitOpinion(amount: String!, documentID: ID!, onModel: String!, opinion: String!): String
    submitVote(onModel: String!, documentID: ID!, amount: Float!, upVote: Boolean!): String

    approveOpinion(_id: ID!, approved: Boolean!, approvalCommentary: String!): Boolean

    submitEditBulletPoint(amount: String!, bulletPointID: ID!, bulletPointContent: String!): String
    submitEditResource(amount: String!, resourceID: ID!, resourceTitle: String!, resourcePath: String!, resourceMedia: String!): String
    addBulletPoint(slug: String!, pro: Boolean!, content: String!): BulletPoint
}